import React, { useState, useEffect } from 'react';
import { supabase } from '@/lib/supabase';

interface Recipe {
  title: string;
  ingredients: string[];
  instructions: string[];
  prepTime?: string;
  cookTime?: string;
  difficulty?: string;
  description?: string;
  servings?: number;
  image?: string;
  totalTime?: string;
  cuisine?: string;
  tags?: string[];
  rating?: number;
  reviews?: number;
}

interface RecipeCardProps {
  recipe: Recipe;
  onClose?: () => void;
}

export default function RecipeCard({ recipe, onClose }: RecipeCardProps) {
  const [showSavedPopup, setShowSavedPopup] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [isAlreadySaved, setIsAlreadySaved] = useState(false);
  const [checkingSavedStatus, setCheckingSavedStatus] = useState(false);
  const [showShareModal, setShowShareModal] = useState(false);

  // Check if recipe is already saved when component mounts
  useEffect(() => {
    const checkSavedStatus = async () => {
      if (!onClose) return; // Only check for modal version
      
      setCheckingSavedStatus(true);
      try {
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) return;

        const res = await fetch(`/api/recipes/check?userId=${user.id}&title=${encodeURIComponent(recipe.title)}`);
        const result = await res.json();
        if (result.success) {
          setIsAlreadySaved(result.isSaved);
        }
      } catch (error) {
        console.error('Error checking saved status:', error);
      } finally {
        setCheckingSavedStatus(false);
      }
    };

    checkSavedStatus();
  }, [recipe.title, onClose]);

  const handleSave = async () => {
    setSaving(true);
    setError('');
    // Get user
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      setError('You must be signed in to save recipes!');
      setSaving(false);
      return;
    }
    try {
      const res = await fetch('/api/recipes/saved', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ userId: user.id, recipe }),
      });
      const contentType = res.headers.get('content-type');
      if (contentType && contentType.includes('application/json')) {
        const result = await res.json();
        if (result.success) {
          setShowSavedPopup(true);
          setTimeout(() => setShowSavedPopup(false), 1200);
          setIsAlreadySaved(true); // Update the saved status
        } else {
          setError(result.message || result.error || 'Failed to save recipe.');
        }
      } else {
        const text = await res.text();
        setError('Server error: ' + text.substring(0, 200));
        console.error('Non-JSON response:', text);
      }
    } catch (e: unknown) {
      const error = e as Error;
      setError(error.message || 'Failed to save recipe.');
    }
    setSaving(false);
  };

  // Share functions
  const shareRecipe = (platform: string) => {
    const recipeText = `Check out this amazing recipe: ${recipe.title}!\n\n${recipe.description || ''}\n\nIngredients:\n${recipe.ingredients.slice(0, 3).join('\n')}${recipe.ingredients.length > 3 ? '\n...and more!' : ''}\n\nGenerated by DIY Recipe Generator 🍽️`;
    const encodedText = encodeURIComponent(recipeText);
    const currentUrl = window.location.href;
    
    switch (platform) {
      case 'whatsapp':
        window.open(`https://wa.me/?text=${encodedText}`, '_blank');
        break;
      case 'facebook':
        window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodedText}`, '_blank');
        break;
      case 'twitter':
        window.open(`https://twitter.com/intent/tweet?text=${encodedText}`, '_blank');
        break;
      case 'instagram':
        // Instagram doesn't have direct sharing API, so we'll copy to clipboard
        navigator.clipboard.writeText(recipeText);
        alert('Recipe copied to clipboard! You can now paste it on Instagram.');
        break;
      case 'telegram':
        window.open(`https://t.me/share/url?url=${currentUrl}&text=${encodedText}`, '_blank');
        break;
      case 'email':
        window.open(`mailto:?subject=${encodeURIComponent('Check out this recipe!')}&body=${encodedText}`, '_blank');
        break;
      case 'copy':
        navigator.clipboard.writeText(recipeText);
        alert('Recipe copied to clipboard!');
        break;
      default:
        // Native sharing if available
        if (navigator.share) {
          navigator.share({
            title: recipe.title,
            text: recipeText,
            url: currentUrl
          });
        }
    }
    setShowShareModal(false);
  };

  // If onClose is not provided, render as a preview card
  if (!onClose) {
    return (
      <div className="bg-gradient-to-br from-yellow-50 to-yellow-100 border-2 border-yellow-200 rounded-3xl shadow-xl overflow-hidden hover:shadow-2xl hover:scale-105 transition-all duration-300 cursor-pointer">
        
        <div className="p-6">
          <div className="text-center">
            <div className="text-4xl mb-3">🍽️</div>
            <h3 className="text-xl font-pacifico text-yellow-700 mb-2">{recipe.title}</h3>
            {recipe.description && (
              <p className="text-yellow-600 text-sm mb-3 italic line-clamp-2">{recipe.description}</p>
            )}
            
            {/* Trust indicators */}
            <div className="flex justify-center gap-2 mb-3">
              {recipe.cookTime && (
                <span className="bg-yellow-100 text-yellow-700 px-3 py-1 rounded-full text-xs font-bold border border-yellow-200">
                  ⏱️ {recipe.cookTime}
                </span>
              )}
              {recipe.difficulty && (
                <span className="bg-yellow-100 text-yellow-700 px-3 py-1 rounded-full text-xs font-bold border border-yellow-200">
                  📊 {recipe.difficulty}
                </span>
              )}
              {recipe.cuisine && (
                <span className="bg-yellow-100 text-yellow-700 px-3 py-1 rounded-full text-xs font-bold border border-yellow-200">
                  🌍 {recipe.cuisine}
                </span>
              )}
            </div>
            
            {/* Trust badge */}
            <div className="flex justify-center mb-3">
              <div className="bg-green-50 text-green-700 px-3 py-1 rounded-full text-xs font-bold border border-green-200 flex items-center gap-1">
                <span>✅</span> Recipe Verified
              </div>
            </div>
            
            {/* Reviews indicator */}
            {recipe.reviews && (
              <div className="text-xs text-gray-500 mb-3">
                {recipe.reviews} reviews • Community Approved
              </div>
            )}
            
            <div className="bg-yellow-200 text-yellow-800 px-4 py-2 rounded-full text-sm font-semibold inline-block border border-yellow-300">
              Click to view full recipe! 👀
            </div>
          </div>
        </div>
      </div>
    );
  }
  // Full modal version
  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex justify-center items-center z-50 p-2 sm:p-4">
      <div className="bg-white rounded-2xl sm:rounded-3xl shadow-2xl w-full max-w-sm sm:max-w-4xl max-h-[95vh] font-quicksand relative flex flex-col">
        
        {/* Close button - responsive positioning */}
        <button 
          onClick={onClose} 
          className="absolute top-2 right-2 sm:top-4 sm:right-4 z-10 bg-white hover:bg-gray-50 rounded-full p-1.5 sm:p-2 transition-all duration-200 text-pink-500 border-2 border-pink-200 shadow-lg"
        >
          <svg className="w-4 h-4 sm:w-6 sm:h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>

        {/* Scrollable content area - responsive padding */}
        <div className="overflow-y-auto flex-1 p-4 pt-12 sm:p-8 sm:pt-16">
          
          {/* Recipe Title and Info */}
          <div className="text-center mb-6 sm:mb-8">
            <div className="text-4xl sm:text-6xl mb-2 sm:mb-4">🍽️</div>
            <h2 className="text-2xl sm:text-4xl font-nunito font-black mb-2 sm:mb-4 text-green-800 uppercase tracking-wider px-2">{recipe.title}</h2>
            {recipe.description && (
              <p className="text-gray-600 text-base sm:text-lg italic font-inter mb-3 sm:mb-4 px-2">{recipe.description}</p>
            )}
            
            {/* Recipe metadata - responsive grid */}
            <div className="flex justify-center gap-2 sm:gap-3 mb-4 sm:mb-6 flex-wrap px-2">
              <div className="bg-green-50 text-green-700 px-2 sm:px-4 py-1 sm:py-2 rounded-full text-xs sm:text-sm font-bold border border-green-200 flex items-center gap-1">
                <span>✅</span> <span className="hidden sm:inline">Recipe </span>Verified
              </div>
              {recipe.cookTime && (
                <span className="bg-orange-100 text-orange-700 px-2 sm:px-4 py-1 sm:py-2 rounded-full text-xs sm:text-sm font-bold">
                  ⏱️ {recipe.cookTime}
                </span>
              )}
              {recipe.difficulty && (
                <span className="bg-blue-100 text-blue-700 px-2 sm:px-4 py-1 sm:py-2 rounded-full text-xs sm:text-sm font-bold">
                  📊 {recipe.difficulty}
                </span>
              )}
              {recipe.servings && (
                <span className="bg-purple-100 text-purple-700 px-2 sm:px-4 py-1 sm:py-2 rounded-full text-xs sm:text-sm font-bold">
                  👥 <span className="hidden sm:inline">Serves </span>{recipe.servings}
                </span>
              )}
            </div>
            
            {/* Community feedback - responsive text */}
            <div className="text-center mb-4 sm:mb-6 px-2">
              <div className="text-xs sm:text-sm text-gray-600 mb-1 sm:mb-2">
                <span className="font-semibold">Community Approved</span> • <span className="hidden sm:inline">Tested by </span>Home Cooks
              </div>
              <div className="flex justify-center items-center gap-2 text-xs sm:text-sm text-gray-500">
                <span>⭐⭐⭐⭐⭐</span>
                <span className="hidden sm:inline">Highly Rated Recipe</span>
                <span className="sm:hidden">5★ Recipe</span>
              </div>
            </div>
          </div>
          {/* Ingredients */}
          <div className="mb-6 sm:mb-8">
            <div className="bg-gradient-to-r from-pink-50 to-yellow-50 border-2 sm:border-4 border-pink-200 rounded-xl sm:rounded-2xl p-4 sm:p-6">
              <h3 className="text-xl sm:text-3xl text-green-700 mb-4 sm:mb-6 text-center font-bold">
                🛒 What You'll Need
              </h3>
              <ul className="space-y-2 sm:space-y-3">
                {recipe.ingredients.map((ingredient, index) => (
                  <li key={index} className="flex items-start gap-2 sm:gap-3 text-gray-800 text-sm sm:text-base">
                    <span className="bg-pink-500 text-white rounded-full w-5 h-5 sm:w-6 sm:h-6 flex items-center justify-center text-xs sm:text-sm font-bold flex-shrink-0 mt-0.5">
                      {index + 1}
                    </span>
                    <span className="font-medium leading-relaxed">{ingredient}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Instructions */}
          <div className="mb-6 sm:mb-8">
            <div className="bg-gradient-to-r from-blue-50 to-green-50 border-2 sm:border-4 border-green-200 rounded-xl sm:rounded-2xl p-4 sm:p-6">
              <h3 className="text-xl sm:text-3xl text-green-700 mb-4 sm:mb-6 text-center font-bold">
                👩‍🍳 Let's Cook Together!
              </h3>
              <div className="space-y-4 sm:space-y-6">
                {recipe.instructions.map((instruction, index) => (
                  <div key={index} className="flex items-start gap-3 sm:gap-4">
                    <span className="bg-green-500 text-white rounded-full w-6 h-6 sm:w-8 sm:h-8 flex items-center justify-center text-sm sm:text-lg font-bold flex-shrink-0 mt-1">
                      {index + 1}
                    </span>
                    <div className="flex-1">
                      <p className="text-gray-800 leading-relaxed font-medium text-sm sm:text-base">
                        {enhanceInstruction(instruction, index + 1)}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {error && <div className="text-red-500 text-sm mt-4 text-center bg-red-50 p-3 rounded-lg">{error}</div>}
        </div>

        {/* Sticky action buttons at bottom - responsive */}
        <div className="sticky bottom-0 bg-white border-t-2 border-gray-100 p-3 sm:p-4 rounded-b-2xl sm:rounded-b-3xl">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 sm:gap-4">
            <button
              className={`py-3 sm:py-4 px-4 sm:px-6 rounded-xl sm:rounded-2xl transition-all duration-300 font-bold text-sm sm:text-lg shadow-lg hover:shadow-xl transform hover:scale-105 border-2 sm:border-4 ${
                isAlreadySaved 
                  ? 'bg-green-100 text-green-800 border-green-300 cursor-not-allowed' 
                  : 'bg-yellow-100 text-yellow-800 border-yellow-300 hover:bg-yellow-200'
              }`}
              onClick={handleSave}
              disabled={saving || isAlreadySaved || checkingSavedStatus}
            >
              {checkingSavedStatus ? (
                <>🔄 <span className="hidden sm:inline">Checking...</span><span className="sm:hidden">...</span></>
              ) : isAlreadySaved ? (
                <>✅ <span className="hidden sm:inline">Saved to Cookbook</span><span className="sm:hidden">Saved</span></>
              ) : (
                <>💛 <span className="hidden sm:inline">Save to My Cookbook</span><span className="sm:hidden">Save</span></>
              )}
              {saving && <span className="ml-2 animate-spin">⏳</span>}
            </button>
            <button 
              onClick={() => setShowShareModal(true)}
              className="py-3 sm:py-4 px-4 sm:px-6 rounded-xl sm:rounded-2xl transition-all duration-300 font-bold text-sm sm:text-lg shadow-lg hover:shadow-xl transform hover:scale-105 border-2 sm:border-4 bg-pink-100 text-pink-800 border-pink-300 hover:bg-pink-200"
            >
              📤 <span className="hidden sm:inline">Share with Friends</span><span className="sm:hidden">Share</span>
            </button>
          </div>
        </div>
      </div>

      {/* Saved popup animation */}
      {showSavedPopup && (
        <div className="fixed top-16 left-1/2 -translate-x-1/2 z-50">
          <div className="relative flex items-center justify-center">
            <div className="animate-burst-pop bg-pink-400 text-white font-bold px-8 py-4 rounded-full shadow-lg text-xl flex items-center gap-2">
              <span role="img" aria-label="sparkle">✨</span> Saved!
            </div>
            {/* Drops */}
            <span className="absolute -top-3 left-1/2 -translate-x-1/2 w-3 h-3 bg-pink-300 rounded-full animate-drop1"></span>
            <span className="absolute -bottom-3 left-1/2 -translate-x-1/2 w-3 h-3 bg-pink-300 rounded-full animate-drop2"></span>
            <span className="absolute top-1/2 -left-3 -translate-y-1/2 w-3 h-3 bg-pink-300 rounded-full animate-drop3"></span>
            <span className="absolute top-1/2 -right-3 -translate-y-1/2 w-3 h-3 bg-pink-300 rounded-full animate-drop4"></span>
          </div>
        </div>
      )}

      {/* Share Modal - responsive */}
      {showShareModal && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex justify-center items-center z-[60] p-2 sm:p-4">
          <div className="bg-white rounded-2xl sm:rounded-3xl shadow-2xl p-4 sm:p-8 max-w-xs sm:max-w-md w-full border-2 sm:border-4 border-pink-200">
            <div className="text-center mb-4 sm:mb-6">
              <h3 className="text-xl sm:text-2xl font-bold text-gray-800 mb-2">Share Recipe</h3>
              <p className="text-gray-600 text-sm sm:text-base">Share "{recipe.title}" with your friends!</p>
            </div>
            
            <div className="grid grid-cols-2 gap-2 sm:gap-4 mb-4 sm:mb-6">
              <button
                onClick={() => shareRecipe('whatsapp')}
                className="flex flex-col items-center gap-1 sm:gap-2 p-2 sm:p-4 rounded-xl hover:bg-green-50 transition-all duration-200 border-2 border-transparent hover:border-green-200"
              >
                <div className="w-8 h-8 sm:w-12 sm:h-12 bg-green-500 rounded-full flex items-center justify-center text-white text-sm sm:text-xl">
                  📱
                </div>
                <span className="text-xs sm:text-sm font-medium text-gray-700">WhatsApp</span>
              </button>
              
              <button
                onClick={() => shareRecipe('facebook')}
                className="flex flex-col items-center gap-1 sm:gap-2 p-2 sm:p-4 rounded-xl hover:bg-blue-50 transition-all duration-200 border-2 border-transparent hover:border-blue-200"
              >
                <div className="w-8 h-8 sm:w-12 sm:h-12 bg-blue-600 rounded-full flex items-center justify-center text-white text-sm sm:text-xl">
                  📘
                </div>
                <span className="text-xs sm:text-sm font-medium text-gray-700">Facebook</span>
              </button>
              
              <button
                onClick={() => shareRecipe('twitter')}
                className="flex flex-col items-center gap-1 sm:gap-2 p-2 sm:p-4 rounded-xl hover:bg-blue-50 transition-all duration-200 border-2 border-transparent hover:border-blue-200"
              >
                <div className="w-8 h-8 sm:w-12 sm:h-12 bg-blue-400 rounded-full flex items-center justify-center text-white text-sm sm:text-xl">
                  🐦
                </div>
                <span className="text-xs sm:text-sm font-medium text-gray-700">Twitter</span>
              </button>
              
              <button
                onClick={() => shareRecipe('instagram')}
                className="flex flex-col items-center gap-1 sm:gap-2 p-2 sm:p-4 rounded-xl hover:bg-pink-50 transition-all duration-200 border-2 border-transparent hover:border-pink-200"
              >
                <div className="w-8 h-8 sm:w-12 sm:h-12 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full flex items-center justify-center text-white text-sm sm:text-xl">
                  📷
                </div>
                <span className="text-xs sm:text-sm font-medium text-gray-700">Instagram</span>
              </button>
              
              <button
                onClick={() => shareRecipe('telegram')}
                className="flex flex-col items-center gap-1 sm:gap-2 p-2 sm:p-4 rounded-xl hover:bg-blue-50 transition-all duration-200 border-2 border-transparent hover:border-blue-200"
              >
                <div className="w-8 h-8 sm:w-12 sm:h-12 bg-blue-500 rounded-full flex items-center justify-center text-white text-sm sm:text-xl">
                  ✈️
                </div>
                <span className="text-xs sm:text-sm font-medium text-gray-700">Telegram</span>
              </button>
              
              <button
                onClick={() => shareRecipe('email')}
                className="flex flex-col items-center gap-1 sm:gap-2 p-2 sm:p-4 rounded-xl hover:bg-gray-50 transition-all duration-200 border-2 border-transparent hover:border-gray-200"
              >
                <div className="w-8 h-8 sm:w-12 sm:h-12 bg-gray-600 rounded-full flex items-center justify-center text-white text-sm sm:text-xl">
                  📧
                </div>
                <span className="text-xs sm:text-sm font-medium text-gray-700">Email</span>
              </button>
            </div>
            
            <div className="flex gap-2 sm:gap-3">
              <button
                onClick={() => shareRecipe('copy')}
                className="flex-1 bg-gray-100 hover:bg-gray-200 text-gray-800 py-2 sm:py-3 px-3 sm:px-4 rounded-xl transition-all duration-200 font-medium text-sm sm:text-base"
              >
                📋 Copy Recipe
              </button>
              <button
                onClick={() => setShowShareModal(false)}
                className="flex-1 bg-pink-500 hover:bg-pink-600 text-white py-2 sm:py-3 px-3 sm:px-4 rounded-xl transition-all duration-200 font-medium text-sm sm:text-base"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// Helper function to make instructions more friendly and detailed
function enhanceInstruction(instruction: string, stepNumber: number): string {
  const friendlyPhrases = [
    "Alright, let's start! ",
    "Now here comes the fun part - ",
    "Next up, we're going to ",
    "Time for step " + stepNumber + "! ",
    "Here's where it gets exciting - ",
    "Don\\'t worry, this part is easy! ",
    "You\\'ve got this! Now ",
    "Almost there! Next, ",
    "This is my favorite part - ",
    "Trust the process and "
  ];
  
  const encouragements = [
    " (You're doing great!)",
    " (Don\\'t rush this part - take your time!)",
    " (This is where the magic happens!)",
    " (Your kitchen probably smells amazing right now!)",
    " (Pro tip: taste as you go!)",
    " (Looking good so far!)",
    " (You're almost a chef!)",
    " (This is the secret to making it perfect!)"
  ];
  
  // Add friendly intro occasionally
  let enhanced = instruction;
  if (Math.random() > 0.7) {
    const randomPhrase = friendlyPhrases[Math.floor(Math.random() * friendlyPhrases.length)];
    enhanced = randomPhrase + instruction.toLowerCase();
  }
  
  // Add encouragement occasionally
  if (Math.random() > 0.6) {
    const randomEncouragement = encouragements[Math.floor(Math.random() * encouragements.length)];
    enhanced += randomEncouragement;
  }
  
  return enhanced;
}
